import { mutation, query } from "./_generated/server.js";
import { v } from "convex/values";
import { createProviderSecretPort, redactIntegrationPayload, verifyWebhook, type IntegrationProvider } from "../packages/adapters/src/integrations/index.js";

const provider = v.union(v.literal("composio"), v.literal("sendblue"), v.literal("apple"));
const deliveryState = v.union(v.literal("queued"), v.literal("sent"), v.literal("delivered"), v.literal("error"), v.literal("unknown"));
const connectionState = v.union(v.literal("pending"), v.literal("active"), v.literal("failed"), v.literal("revoked"));
const terminal = new Set(["delivered", "error"]);
const semanticToolkitVersion = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
async function authorize(ctx: any, workspaceId: any) {
  const identity = await ctx.auth.getUserIdentity(); if (!identity) throw new Error("AUTH_REQUIRED");
  const workspace = await ctx.db.get(workspaceId); if (!workspace || workspace.status !== "active") throw new Error("WORKSPACE_INACTIVE");
  const membership = await ctx.db.query("memberships").withIndex("by_workspace_subject", (q: any) => q.eq("workspaceId", workspaceId).eq("subject", identity.subject)).unique();
  if (!membership) throw new Error("TENANT_ACCESS_DENIED"); if (membership.status === "stale") throw new Error("MEMBERSHIP_STALE"); if (membership.status === "revoked") throw new Error("MEMBERSHIP_REVOKED"); return identity;
}
export const upsertConnection = mutation({ args: { workspaceId: v.id("workspaces"), connectionId: v.string(), provider, scopes: v.array(v.string()), toolkitVersion: v.string(), now: v.number(), state: v.optional(connectionState) }, handler: async (ctx, args) => { if (args.provider === "composio" && !semanticToolkitVersion.test(args.toolkitVersion)) throw new Error("COMPOSIO_TOOLKIT_VERSION_INVALID"); const identity = await authorize(ctx, args.workspaceId); const existing = await ctx.db.query("integrationConnections").withIndex("by_workspace_connection", (q: any) => q.eq("workspaceId", args.workspaceId).eq("connectionId", args.connectionId)).unique(); const state = args.state ?? "active"; if (existing) { if (existing.userId !== identity.subject || existing.provider !== args.provider) throw new Error("INTEGRATION_CONNECTION_DENIED"); await ctx.db.patch(existing._id, { scopes: args.scopes, toolkitVersion: args.toolkitVersion, state, updatedAt: args.now }); return { state, replay: true as const }; } const connectionRecordId = await ctx.db.insert("integrationConnections", { workspaceId: args.workspaceId, connectionId: args.connectionId, provider: args.provider, userId: identity.subject, scopes: args.scopes, toolkitVersion: args.toolkitVersion, state: "pending", createdAt: args.now, updatedAt: args.now }); await ctx.db.patch(connectionRecordId, { state }); return { state, replay: false as const }; } });
export const getConnection = query({ args: { workspaceId: v.id("workspaces"), connectionId: v.string() }, handler: async (ctx, args) => { const identity = await authorize(ctx, args.workspaceId); const connection = await ctx.db.query("integrationConnections").withIndex("by_workspace_connection", (q: any) => q.eq("workspaceId", args.workspaceId).eq("connectionId", args.connectionId)).unique(); if (connection && connection.userId !== identity.subject) throw new Error("INTEGRATION_CONNECTION_DENIED"); return connection; } });
export const admitWebhook = mutation({ args: { workspaceId: v.id("workspaces"), provider, payload: v.string(), signature: v.string(), timestamp: v.number(), now: v.number() }, handler: async (ctx, args) => { await authorize(ctx, args.workspaceId); const providerSecrets = createProviderSecretPort({ composio: process.env.COMPOSIO_WEBHOOK_SECRET, sendblue: process.env.SENDBLUE_WEBHOOK_SECRET, apple: process.env.APPLE_WEBHOOK_SECRET }); const parsed = await verifyWebhook({ provider: args.provider as IntegrationProvider, payload: args.payload, signature: args.signature, providerSecrets, timestamp: args.timestamp, now: args.now, replayKeys: new Set() }); if (!parsed.accepted) return parsed; const existing = await ctx.db.query("integrationInbox").withIndex("by_workspace_provider_event", (q: any) => q.eq("workspaceId", args.workspaceId).eq("provider", args.provider).eq("eventId", parsed.eventId)).unique(); if (existing) return { accepted: false as const, code: "WEBHOOK_REPLAY" }; await ctx.db.insert("integrationInbox", { workspaceId: args.workspaceId, provider: args.provider, eventId: parsed.eventId, payload: redactIntegrationPayload(args.payload), receivedAt: args.now, timestamp: args.timestamp, status: "accepted" }); return { accepted: true as const, replay: false as const }; } });
export const queueDelivery = mutation({ args: { workspaceId: v.id("workspaces"), connectionId: v.string(), idempotencyKey: v.string(), destination: v.string(), now: v.number() }, handler: async (ctx, args) => { const identity = await authorize(ctx, args.workspaceId); const connection = await ctx.db.query("integrationConnections").withIndex("by_workspace_connection", (q: any) => q.eq("workspaceId", args.workspaceId).eq("connectionId", args.connectionId)).unique(); if (!connection || connection.userId !== identity.subject || connection.state !== "active") throw new Error("INTEGRATION_CONNECTION_DENIED"); const existing = await ctx.db.query("integrationOutbox").withIndex("by_workspace_key", (q: any) => q.eq("workspaceId", args.workspaceId).eq("idempotencyKey", args.idempotencyKey)).unique(); if (existing) return { state: existing.state, replay: true as const }; await ctx.db.insert("integrationOutbox", { ...args, provider: connection.provider, state: "queued", attempts: 0, fence: 0, nextAttemptAt: args.now, auditCostMicros: 0, auditLatencyMs: 0 }); return { state: "queued" as const, replay: false as const }; } });
export const claimDelivery = mutation({ args: { workspaceId: v.id("workspaces"), idempotencyKey: v.string(), workerId: v.string(), now: v.number(), leaseMs: v.number() }, handler: async (ctx, args) => { await authorize(ctx, args.workspaceId); const record = await ctx.db.query("integrationOutbox").withIndex("by_workspace_key", (q: any) => q.eq("workspaceId", args.workspaceId).eq("idempotencyKey", args.idempotencyKey)).unique(); if (!record) throw new Error("INTEGRATION_DELIVERY_NOT_FOUND"); if (terminal.has(record.state) || (record.nextAttemptAt !== undefined && record.nextAttemptAt > args.now) || (record.leaseExpiresAt && record.leaseExpiresAt > args.now)) return { acquired: false as const, fence: record.fence }; const fence = record.fence + 1; await ctx.db.patch(record._id, { leaseOwner: args.workerId, leaseExpiresAt: args.now + args.leaseMs, fence, attempts: record.attempts + 1 }); return { acquired: true as const, fence }; } });
export const reconcileDelivery = mutation({ args: { workspaceId: v.id("workspaces"), idempotencyKey: v.string(), fence: v.number(), providerDeliveryId: v.string(), state: deliveryState, costMicros: v.number(), latencyMs: v.number(), now: v.number() }, handler: async (ctx, args) => { await authorize(ctx, args.workspaceId); const record = await ctx.db.query("integrationOutbox").withIndex("by_workspace_key", (q: any) => q.eq("workspaceId", args.workspaceId).eq("idempotencyKey", args.idempotencyKey)).unique(); if (!record || record.fence !== args.fence) throw new Error("OUTBOX_FENCE_DENIED"); if (terminal.has(record.state) || args.state === "queued") return { state: record.state, idempotencyKey: args.idempotencyKey }; const retryAt = args.state === "unknown" ? args.now + Math.min(300_000, 1_000 * 2 ** record.attempts) : undefined; await ctx.db.patch(record._id, { providerDeliveryId: args.providerDeliveryId, state: args.state, reconciledAt: args.now, auditCostMicros: args.costMicros, auditLatencyMs: args.latencyMs, nextAttemptAt: retryAt, leaseExpiresAt: undefined }); return { state: args.state, idempotencyKey: args.idempotencyKey }; } });
