import { internalMutation, mutation } from "./_generated/server.js";
import { v } from "convex/values";
import { authorizeTenantAccess, type Membership } from "../packages/contracts/src/foundation.js";

const tiers = v.union(v.literal("short"), v.literal("long"), v.literal("permanent"));
const consents = v.union(v.literal("granted"), v.literal("withdrawn"), v.literal("expired"));
const provenance = v.union(v.literal("trusted"), v.literal("untrusted"));
const conflicts = v.union(v.literal("clear"), v.literal("conflicted"));
const reviews = v.union(v.literal("approved"), v.literal("pending"), v.literal("rejected"));
const poisoning = v.union(v.literal("clean"), v.literal("poisoned"));
const jobStatus = v.union(v.literal("queued"), v.literal("queued_offline"), v.literal("running"), v.literal("completed"), v.literal("failed"));
const defaultRebuildMaxAttempts = 2;

function fingerprint(workspaceId: string, content: string) {
  let hash = 2166136261;
  for (const char of `${workspaceId}:${content.trim().toLowerCase()}`) hash = Math.imul(hash ^ char.charCodeAt(0), 16777619);
  return `fnv1a-${(hash >>> 0).toString(16)}`;
}
function canonicalContent(value: string) { return value.trim().toLowerCase().replace(/\s+/g, " "); }
function restrictiveConsent(left: "granted" | "withdrawn" | "expired", right: "granted" | "withdrawn" | "expired") {
  const rank = { granted: 0, expired: 1, withdrawn: 2 } as const;
  return rank[left] >= rank[right] ? left : right;
}
function restrictive<T extends string>(left: T, right: T, unsafe: T) { return left === unsafe || right === unsafe ? unsafe : left; }
async function recordMemoryAudit(ctx: any, workspaceId: any, actorId: string, action: string, outcome: "accepted" | "denied", code?: string) {
  await ctx.db.insert("memoryAuditEvents", { workspaceId, actorId, action, outcome, ...(code ? { code } : {}) });
}

async function requireAccess(ctx: any, workspaceId: any, mode: "read" | "write", action: string): Promise<{ allowed: true; identity: { subject: string } } | { allowed: false; outcome: "denied"; code: string }> {
  const identity = await ctx.auth.getUserIdentity();
  if (!identity) { await recordMemoryAudit(ctx, workspaceId, "anonymous", action, "denied", "AUTH_REQUIRED"); return { allowed: false, outcome: "denied", code: "AUTH_REQUIRED" }; }
  const workspace = await ctx.db.get(workspaceId);
  if (!workspace || workspace.status !== "active") { await recordMemoryAudit(ctx, workspaceId, identity.subject, action, "denied", "WORKSPACE_INACTIVE"); return { allowed: false, outcome: "denied", code: "WORKSPACE_INACTIVE" }; }
  const membership = await ctx.db.query("memberships").withIndex("by_workspace_subject", (q: any) => q.eq("workspaceId", workspaceId).eq("subject", identity.subject)).unique() ?? await ctx.db.query("memberships").withIndex("by_subject", (q: any) => q.eq("subject", identity.subject)).first();
  const decision = authorizeTenantAccess(membership as Membership | undefined, workspaceId, mode);
  if (!decision.allowed) { await recordMemoryAudit(ctx, workspaceId, identity.subject, action, "denied", decision.code); return { allowed: false, outcome: "denied", code: decision.code }; }
  await recordMemoryAudit(ctx, workspaceId, identity.subject, action, "accepted");
  return { allowed: true, identity };
}
const recordArgs = { workspaceId: v.id("workspaces"), sourceId: v.string(), content: v.string(), tier: tiers, consent: consents, retentionUntil: v.number(), provenance, sourceAt: v.number(), embeddingModel: v.string(), embeddingVersion: v.string(), embeddingDimension: v.number(), embeddingNormalized: v.boolean(), semanticKey: v.string(), conflictStatus: conflicts, reviewStatus: reviews, poisoningStatus: poisoning };

export const ingest = mutation({ args: recordArgs, handler: async (ctx, args) => {
  const access = await requireAccess(ctx, args.workspaceId, "write", "memory.ingest"); if (!access.allowed) return access; const identity = access.identity;
  const key = fingerprint(String(args.workspaceId), args.content);
  const existing = await ctx.db.query("memoryRecords").withIndex("by_workspace_fingerprint", (q) => q.eq("workspaceId", args.workspaceId).eq("fingerprint", key)).unique();
  if (existing) {
    if (existing.canonicalContent !== canonicalContent(args.content)) throw new Error("FINGERPRINT_COLLISION");
    if (existing.semanticKey !== args.semanticKey) throw new Error("SEMANTIC_INCOMPATIBLE");
    const sourceIds = [...new Set([...existing.sourceIds, args.sourceId])].sort();
    const mergedReviewStatus: "approved" | "pending" | "rejected" = existing.reviewStatus === "rejected" || args.reviewStatus === "rejected" ? "rejected" : restrictive(existing.reviewStatus, args.reviewStatus, "pending");
    const merged = { sourceAt: Math.max(existing.sourceAt, args.sourceAt), sourceIds, lineage: [...new Set([...existing.lineage, ...sourceIds])].sort(), provenanceLineage: [...existing.provenanceLineage, { sourceId: args.sourceId, provenance: args.provenance }].sort((a, b) => a.sourceId.localeCompare(b.sourceId)), consent: restrictiveConsent(existing.consent, args.consent), retentionUntil: Math.min(existing.retentionUntil, args.retentionUntil), provenance: restrictive(existing.provenance, args.provenance, "untrusted"), conflictStatus: restrictive(existing.conflictStatus, args.conflictStatus, "conflicted"), reviewStatus: mergedReviewStatus, reviewLineage: [...existing.reviewLineage, { status: args.reviewStatus, subject: identity.subject }], poisoningStatus: restrictive(existing.poisoningStatus, args.poisoningStatus, "poisoned") };
    await ctx.db.patch(existing._id, merged);
    return { status: "merged" as const, memoryId: existing._id, fingerprint: key, ...merged };
  }
  const semanticPeer = await ctx.db.query("memoryRecords").withIndex("by_workspace_semantic", (q) => q.eq("workspaceId", args.workspaceId).eq("semanticKey", args.semanticKey)).filter((q) => q.and(q.neq(q.field("deleted"), true), q.neq(q.field("canonicalContent"), canonicalContent(args.content)))).first();
  const { sourceId, ...record } = args;
  const conflicted = Boolean(semanticPeer);
  const memoryId = await ctx.db.insert("memoryRecords", { ...record, fingerprint: key, canonicalContent: canonicalContent(args.content), sourceIds: [sourceId], lineage: [sourceId], provenanceLineage: [{ sourceId, provenance: args.provenance }], conflictStatus: conflicted ? "conflicted" : args.conflictStatus, reviewStatus: conflicted ? "pending" : args.reviewStatus, reviewLineage: [{ status: conflicted ? "pending" : args.reviewStatus, subject: identity.subject }], deleted: false, superseded: false, supersessionLineage: [{ status: "none", reason: "created" }] });
  if (semanticPeer) {
    await ctx.db.patch(semanticPeer._id, { conflictStatus: "conflicted", reviewStatus: "pending", reviewLineage: [...semanticPeer.reviewLineage, { status: "pending", subject: identity.subject }] });
    const conflictId = await ctx.db.insert("memoryConflicts", { workspaceId: args.workspaceId, semanticKey: args.semanticKey, existingMemoryId: semanticPeer._id, conflictingMemoryId: memoryId, existingFingerprint: semanticPeer.fingerprint, conflictingFingerprint: key, existingProvenance: semanticPeer.provenance, conflictingProvenance: args.provenance, status: "pending", supersessionStatus: "none", reviewLineage: [{ status: "pending", subject: identity.subject }], supersessionLineage: [{ status: "none", reason: "semantic-content-mismatch" }] });
    return { status: "conflicted" as const, memoryId, fingerprint: key, conflictId };
  }
  return { status: "created" as const, memoryId, fingerprint: key };
} });

export const updateConsent = mutation({ args: { memoryId: v.id("memoryRecords"), consent: consents }, handler: async (ctx, args) => { const record = await ctx.db.get(args.memoryId); if (!record) throw new Error("MEMORY_NOT_FOUND"); const access = await requireAccess(ctx, record.workspaceId, "write", "memory.updateConsent"); if (!access.allowed) return access; await ctx.db.patch(args.memoryId, { consent: args.consent }); } });
export const updateRetention = mutation({ args: { memoryId: v.id("memoryRecords"), retentionUntil: v.number() }, handler: async (ctx, args) => { const record = await ctx.db.get(args.memoryId); if (!record) throw new Error("MEMORY_NOT_FOUND"); const access = await requireAccess(ctx, record.workspaceId, "write", "memory.updateRetention"); if (!access.allowed) return access; await ctx.db.patch(args.memoryId, { retentionUntil: args.retentionUntil, consent: args.retentionUntil < Date.now() ? "expired" : record.consent }); } });
export const supersede = mutation({ args: { memoryId: v.id("memoryRecords"), replacementMemoryId: v.id("memoryRecords"), reason: v.string() }, handler: async (ctx, args) => { const memory = await ctx.db.get(args.memoryId); const replacement = await ctx.db.get(args.replacementMemoryId); if (!memory || !replacement) throw new Error("MEMORY_NOT_FOUND"); const access = await requireAccess(ctx, memory.workspaceId, "write", "memory.supersede"); if (!access.allowed) return access; if (memory.workspaceId !== replacement.workspaceId) { await recordMemoryAudit(ctx, memory.workspaceId, access.identity.subject, "memory.supersede", "denied", "TENANT_MISMATCH"); return { outcome: "denied" as const, code: "TENANT_MISMATCH" }; } await ctx.db.patch(args.memoryId, { superseded: true, supersededBy: args.replacementMemoryId, lineage: [...new Set([...memory.lineage, `superseded:${String(args.replacementMemoryId)}:${args.reason}`])].sort(), supersessionLineage: [...memory.supersessionLineage, { status: "superseded", reason: args.reason, targetMemoryId: args.replacementMemoryId }] }); } });
export const retrieve = mutation({ args: { workspaceId: v.id("workspaces"), now: v.number(), embeddingDimension: v.number(), forAction: v.boolean() }, handler: async (ctx, args) => { const access = await requireAccess(ctx, args.workspaceId, "read", "memory.retrieve"); if (!access.allowed) return access; const all = await ctx.db.query("memoryRecords").withIndex("by_workspace", (q) => q.eq("workspaceId", args.workspaceId)).collect(); if (all.some((record) => !record.deleted && record.embeddingDimension !== args.embeddingDimension)) throw new Error("MIXED_EMBEDDING_DIMENSION"); return all.filter((record) => record.embeddingDimension === args.embeddingDimension && record.consent === "granted" && record.retentionUntil >= args.now && !record.deleted && !record.superseded && record.poisoningStatus === "clean" && record.reviewStatus === "approved" && record.conflictStatus === "clear" && (!args.forAction || record.provenance === "trusted")); } });
export const exportWorkspace = mutation({ args: { workspaceId: v.id("workspaces") }, handler: async (ctx, args) => { const access = await requireAccess(ctx, args.workspaceId, "read", "memory.exportWorkspace"); if (!access.allowed) return access; return { memories: await ctx.db.query("memoryRecords").withIndex("by_workspace", (q) => q.eq("workspaceId", args.workspaceId)).collect() }; } });
export const listConflicts = mutation({ args: { workspaceId: v.id("workspaces") }, handler: async (ctx, args) => { const access = await requireAccess(ctx, args.workspaceId, "read", "memory.listConflicts"); if (!access.allowed) return access; return await ctx.db.query("memoryConflicts").withIndex("by_workspace", (q) => q.eq("workspaceId", args.workspaceId)).collect(); } });
export const deleteWorkspace = mutation({ args: { workspaceId: v.id("workspaces") }, handler: async (ctx, args) => { const access = await requireAccess(ctx, args.workspaceId, "write", "memory.deleteWorkspace"); if (!access.allowed) return access; const [records, conflicts, jobs] = await Promise.all([ctx.db.query("memoryRecords").withIndex("by_workspace", (q) => q.eq("workspaceId", args.workspaceId)).collect(), ctx.db.query("memoryConflicts").withIndex("by_workspace", (q) => q.eq("workspaceId", args.workspaceId)).collect(), ctx.db.query("embeddingRebuildJobs").withIndex("by_workspace", (q) => q.eq("workspaceId", args.workspaceId)).collect()]); for (const row of [...records, ...conflicts, ...jobs]) await ctx.db.delete(row._id); for (const store of ["graph", "index", "cache"] as const) await ctx.db.insert("memoryInvalidations", { workspaceId: args.workspaceId, store, action: "delete_workspace" }); return { deleted: records.length, rebuildJobsDeleted: jobs.length, conflictsDeleted: conflicts.length, invalidations: 3 }; } });
export const startEmbeddingRebuild = mutation({ args: { workspaceId: v.id("workspaces"), model: v.string(), version: v.string(), dimension: v.number(), normalized: v.boolean(), offline: v.boolean() }, handler: async (ctx, args) => { const access = await requireAccess(ctx, args.workspaceId, "write", "memory.startEmbeddingRebuild"); if (!access.allowed) return access; const records = (await ctx.db.query("memoryRecords").withIndex("by_workspace", (q) => q.eq("workspaceId", args.workspaceId)).collect()).filter((record) => !record.deleted).sort((a, b) => a.sourceIds[0].localeCompare(b.sourceIds[0]) || String(a._id).localeCompare(String(b._id))); const queue = records.map((record) => record._id); const targetKey = `${args.model}:${args.version}:${args.dimension}:${args.normalized}`; const existing = await ctx.db.query("embeddingRebuildJobs").withIndex("by_workspace_target", (q) => q.eq("workspaceId", args.workspaceId).eq("targetKey", targetKey)).unique(); if (existing) return { status: existing.status, jobId: existing._id, total: existing.total, completed: existing.completed, queue: existing.queue }; const status = args.offline ? "queued_offline" as const : "queued" as const; const jobId = await ctx.db.insert("embeddingRebuildJobs", { workspaceId: args.workspaceId, targetKey, model: args.model, version: args.version, dimension: args.dimension, normalized: args.normalized, status, total: queue.length, completed: 0, queue, attempts: 0, maxAttempts: defaultRebuildMaxAttempts, nextAttemptAt: 0 }); return { status, jobId, total: queue.length, completed: 0, queue }; } });
export const processEmbeddingRebuild = internalMutation({ args: { jobId: v.id("embeddingRebuildJobs"), now: v.number(), maxRecords: v.optional(v.number()) }, handler: async (ctx, args) => { const job = await ctx.db.get(args.jobId); if (!job) throw new Error("REBUILD_JOB_NOT_FOUND"); if (job.status === "queued_offline" || job.status === "completed" || job.status === "failed") return { status: job.status, completed: job.completed, total: job.total, attempts: job.attempts, failureCode: job.failureCode }; if (args.now < job.nextAttemptAt) throw new Error("REBUILD_RETRY_NOT_DUE"); if (job.dimension <= 0) { const attempts = job.attempts + 1; const status = attempts >= job.maxAttempts ? "failed" as const : "queued" as const; await ctx.db.patch(job._id, { status, attempts, failureCode: "INVALID_EMBEDDING_TARGET", nextAttemptAt: args.now + 1 }); return { status, completed: job.completed, total: job.total, attempts, failureCode: "INVALID_EMBEDDING_TARGET" as const }; } await ctx.db.patch(job._id, { status: "running" }); const end = Math.min(job.total, job.completed + Math.max(1, args.maxRecords ?? job.total)); for (const memoryId of job.queue.slice(job.completed, end)) { const memory = await ctx.db.get(memoryId); if (memory && !memory.deleted) await ctx.db.patch(memoryId, { embeddingModel: job.model, embeddingVersion: job.version, embeddingDimension: job.dimension, embeddingNormalized: job.normalized }); } const status = end === job.total ? "completed" as const : "queued" as const; await ctx.db.patch(job._id, { status, completed: end, failureCode: undefined, nextAttemptAt: args.now }); return { status, completed: end, total: job.total, attempts: job.attempts }; } });
