import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  workspaces: defineTable({ slug: v.string(), status: v.union(v.literal("active"), v.literal("suspended")), version: v.number() }).index("by_slug", ["slug"]),
  memberships: defineTable({ workspaceId: v.id("workspaces"), subject: v.string(), role: v.union(v.literal("viewer"), v.literal("editor"), v.literal("admin")), status: v.union(v.literal("active"), v.literal("stale"), v.literal("revoked")) }).index("by_workspace_subject", ["workspaceId", "subject"]).index("by_subject", ["subject"]),
  commands: defineTable({ workspaceId: v.id("workspaces"), idempotencyKey: v.string(), expectedVersion: v.number(), capability: v.string(), commandId: v.string(), outcome: v.union(v.literal("accepted"), v.literal("denied"), v.literal("conflict")), code: v.optional(v.string()), effectAllowed: v.boolean(), nextVersion: v.number(), actorId: v.string() }).index("by_workspace_key", ["workspaceId", "idempotencyKey"]),
  auditEvents: defineTable({ workspaceId: v.id("workspaces"), commandId: v.string(), decision: v.union(v.literal("accepted"), v.literal("denied"), v.literal("conflict")), immutable: v.literal(true), actorId: v.string() }).index("by_workspace", ["workspaceId"]),
  outbox: defineTable({ workspaceId: v.id("workspaces"), idempotencyKey: v.string(), status: v.union(v.literal("pending"), v.literal("leased"), v.literal("verified"), v.literal("failed")), fence: v.number(), leaseOwner: v.optional(v.string()), leaseExpiresAt: v.number() }).index("by_workspace_key", ["workspaceId", "idempotencyKey"]),
  inbox: defineTable({ workspaceId: v.id("workspaces"), idempotencyKey: v.string(), status: v.literal("accepted") }).index("by_workspace_key", ["workspaceId", "idempotencyKey"]),
  integrationConnections: defineTable({ workspaceId: v.id("workspaces"), connectionId: v.string(), provider: v.union(v.literal("composio"), v.literal("sendblue"), v.literal("apple")), userId: v.string(), scopes: v.array(v.string()), toolkitVersion: v.string(), state: v.union(v.literal("pending"), v.literal("active"), v.literal("revoked"), v.literal("failed")), createdAt: v.number(), updatedAt: v.number() }).index("by_workspace_connection", ["workspaceId", "connectionId"]),
  integrationInbox: defineTable({ workspaceId: v.id("workspaces"), provider: v.union(v.literal("composio"), v.literal("sendblue"), v.literal("apple")), eventId: v.string(), payload: v.string(), receivedAt: v.number(), timestamp: v.number(), status: v.literal("accepted") }).index("by_workspace_provider_event", ["workspaceId", "provider", "eventId"]),
  integrationOutbox: defineTable({ workspaceId: v.id("workspaces"), connectionId: v.string(), idempotencyKey: v.string(), destination: v.string(), now: v.number(), provider: v.union(v.literal("composio"), v.literal("sendblue"), v.literal("apple")), state: v.union(v.literal("queued"), v.literal("sent"), v.literal("delivered"), v.literal("error"), v.literal("unknown")), attempts: v.number(), fence: v.number(), leaseOwner: v.optional(v.string()), leaseExpiresAt: v.optional(v.number()), nextAttemptAt: v.optional(v.number()), providerDeliveryId: v.optional(v.string()), reconciledAt: v.optional(v.number()), auditCostMicros: v.number(), auditLatencyMs: v.number() }).index("by_workspace_key", ["workspaceId", "idempotencyKey"]),
  runs: defineTable({ workspaceId: v.id("workspaces"), runKey: v.string(), state: v.union(v.literal("queued"), v.literal("running"), v.literal("completed"), v.literal("failed"), v.literal("manual_review")), version: v.number(), fence: v.number() }).index("by_workspace_key", ["workspaceId", "runKey"]),
  runtimeEffects: defineTable({ runId: v.id("runs"), idempotencyKey: v.string(), sequence: v.number(), fence: v.number(), outcome: v.union(v.literal("verified"), v.literal("denied"), v.literal("failed"), v.literal("unknown")) }).index("by_run_key", ["runId", "idempotencyKey"]),
  contextSnapshots: defineTable({ workspaceId: v.id("workspaces"), runId: v.id("runs"), snapshotKey: v.string(), budget: v.number(), usedTokens: v.number(), sourceIds: v.array(v.string()), provenance: v.array(v.string()) }).index("by_run_key", ["runId", "snapshotKey"]),
  replayArtifacts: defineTable({ workspaceId: v.id("workspaces"), runId: v.id("runs"), replayKey: v.string(), canonicalState: v.string(), classification: v.union(v.literal("equivalent"), v.literal("different")) }).index("by_run_key", ["runId", "replayKey"]),
  rddReceipts: defineTable({ workspaceId: v.id("workspaces"), runId: v.id("runs"), receiptKey: v.string(), reviewedBytes: v.string(), transitions: v.array(v.string()), evidence: v.array(v.string()), lineage: v.string() }).index("by_workspace_key", ["workspaceId", "receiptKey"]),
  automationSchedules: defineTable({ workspaceId: v.id("workspaces"), scheduleKey: v.string(), timezone: v.string(), nextRunAt: v.number(), version: v.number(), enabled: v.boolean(), maxAttempts: v.number(), deadlineAt: v.number(), quotaLimit: v.number() }).index("by_workspace_key", ["workspaceId", "scheduleKey"]),
  automationRuns: defineTable({ workspaceId: v.id("workspaces"), scheduleId: v.id("automationSchedules"), plannedFor: v.number(), state: v.union(v.literal("queued"), v.literal("leased"), v.literal("retrying"), v.literal("cancelled"), v.literal("completed"), v.literal("manual_review")), version: v.number(), attempts: v.number(), maxAttempts: v.number(), deadlineAt: v.number(), nextAttemptAt: v.number(), fence: v.number(), leaseOwner: v.optional(v.string()), leaseExpiresAt: v.optional(v.number()), failureCode: v.optional(v.string()), diagnostics: v.optional(v.string()) }).index("by_schedule_planned", ["scheduleId", "plannedFor"]).index("by_workspace_state_due", ["workspaceId", "state", "nextAttemptAt"]),
  automationBeats: defineTable({ workspaceId: v.id("workspaces"), tickKey: v.string(), processedAt: v.number() }).index("by_workspace_key", ["workspaceId", "tickKey"]),
  workerLeases: defineTable({ workspaceId: v.id("workspaces"), workerKey: v.string(), owner: v.string(), fence: v.number(), expiresAt: v.number(), recoveryCount: v.number() }).index("by_workspace_key", ["workspaceId", "workerKey"]),
  automationAlerts: defineTable({ workspaceId: v.id("workspaces"), source: v.string(), code: v.string(), createdAt: v.number(), diagnostics: v.string() }).index("by_workspace", ["workspaceId"]),
  memoryRecords: defineTable({ workspaceId: v.id("workspaces"), fingerprint: v.string(), canonicalContent: v.string(), content: v.string(), tier: v.union(v.literal("short"), v.literal("long"), v.literal("permanent")), consent: v.union(v.literal("granted"), v.literal("withdrawn"), v.literal("expired")), retentionUntil: v.number(), provenance: v.union(v.literal("trusted"), v.literal("untrusted")), provenanceLineage: v.array(v.object({ sourceId: v.string(), provenance: v.union(v.literal("trusted"), v.literal("untrusted")) })), sourceAt: v.number(), sourceIds: v.array(v.string()), semanticKey: v.string(), lineage: v.array(v.string()), conflictStatus: v.union(v.literal("clear"), v.literal("conflicted")), reviewStatus: v.union(v.literal("approved"), v.literal("pending"), v.literal("rejected")), reviewLineage: v.array(v.object({ status: v.union(v.literal("approved"), v.literal("pending"), v.literal("rejected")), subject: v.string() })), poisoningStatus: v.union(v.literal("clean"), v.literal("poisoned")), deleted: v.boolean(), superseded: v.boolean(), supersededBy: v.optional(v.id("memoryRecords")), supersessionLineage: v.array(v.object({ status: v.union(v.literal("none"), v.literal("superseded")), reason: v.string(), targetMemoryId: v.optional(v.id("memoryRecords")) })), embeddingModel: v.string(), embeddingVersion: v.string(), embeddingDimension: v.number(), embeddingNormalized: v.boolean() }).index("by_workspace_fingerprint", ["workspaceId", "fingerprint"]).index("by_workspace_semantic", ["workspaceId", "semanticKey"]).index("by_workspace_dimension", ["workspaceId", "embeddingDimension"]).index("by_workspace", ["workspaceId"]),
  memoryConflicts: defineTable({ workspaceId: v.id("workspaces"), semanticKey: v.string(), existingMemoryId: v.id("memoryRecords"), conflictingMemoryId: v.id("memoryRecords"), existingFingerprint: v.string(), conflictingFingerprint: v.string(), existingProvenance: v.union(v.literal("trusted"), v.literal("untrusted")), conflictingProvenance: v.union(v.literal("trusted"), v.literal("untrusted")), status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")), supersessionStatus: v.union(v.literal("none"), v.literal("superseded")), reviewLineage: v.array(v.object({ status: v.union(v.literal("pending"), v.literal("approved"), v.literal("rejected")), subject: v.string() })), supersessionLineage: v.array(v.object({ status: v.union(v.literal("none"), v.literal("superseded")), reason: v.string() })) }).index("by_workspace_semantic", ["workspaceId", "semanticKey"]).index("by_workspace", ["workspaceId"]),
  embeddingRebuildJobs: defineTable({ workspaceId: v.id("workspaces"), targetKey: v.string(), model: v.string(), version: v.string(), dimension: v.number(), normalized: v.boolean(), status: v.union(v.literal("queued"), v.literal("queued_offline"), v.literal("running"), v.literal("completed"), v.literal("failed")), total: v.number(), completed: v.number(), queue: v.array(v.id("memoryRecords")), attempts: v.number(), maxAttempts: v.number(), failureCode: v.optional(v.string()), nextAttemptAt: v.number() }).index("by_workspace_target", ["workspaceId", "targetKey"]).index("by_workspace", ["workspaceId"]),
  memoryAuditEvents: defineTable({ workspaceId: v.id("workspaces"), actorId: v.string(), action: v.string(), outcome: v.union(v.literal("accepted"), v.literal("denied")), code: v.optional(v.string()) }).index("by_workspace", ["workspaceId"]),
  memoryInvalidations: defineTable({ workspaceId: v.id("workspaces"), store: v.union(v.literal("graph"), v.literal("index"), v.literal("cache")), action: v.literal("delete_workspace") }).index("by_workspace", ["workspaceId"])
  ,commercialEntitlements: defineTable({ workspaceId: v.id("workspaces"), plan: v.string(), usageLimit: v.number(), consumedUnits: v.number(), active: v.boolean(), updatedAt: v.number() }).index("by_workspace", ["workspaceId"])
  ,usageLedger: defineTable({ workspaceId: v.id("workspaces"), idempotencyKey: v.string(), units: v.number(), totalUnits: v.number(), recordedAt: v.number(), actorId: v.string() }).index("by_workspace_key", ["workspaceId", "idempotencyKey"])
  ,operationalHealth: defineTable({ workspaceId: v.id("workspaces"), component: v.union(v.literal("database"), v.literal("backup"), v.literal("provider")), healthy: v.boolean(), checkedAt: v.number(), detail: v.string() }).index("by_workspace_component", ["workspaceId", "component"]).index("by_workspace", ["workspaceId"])
  ,operationalAuditEvents: defineTable({ workspaceId: v.id("workspaces"), actorId: v.string(), action: v.string(), metadata: v.string(), createdAt: v.number() }).index("by_workspace", ["workspaceId"])
  ,billingReceipts: defineTable({ workspaceId: v.id("workspaces"), idempotencyKey: v.string(), amountMicros: v.number(), currency: v.string(), provider: v.string(), requestFingerprint: v.string(), status: v.union(v.literal("pending"), v.literal("unknown"), v.literal("settled"), v.literal("rejected")), providerReference: v.optional(v.string()), claimOwner: v.string(), claimedAt: v.number(), leaseExpiresAt: v.number(), fence: v.number(), reconciledAt: v.optional(v.number()) }).index("by_workspace_key", ["workspaceId", "idempotencyKey"])
  ,paymentAuditEvents: defineTable({ workspaceId: v.id("workspaces"), receiptId: v.id("billingReceipts"), actorId: v.string(), action: v.string(), status: v.string(), metadata: v.string(), createdAt: v.number() }).index("by_workspace", ["workspaceId"])
  ,operationalSlo: defineTable({ workspaceId: v.id("workspaces"), availabilityTarget: v.number(), errorBudgetEvents: v.number(), remainingErrorBudget: v.number(), successes: v.number(), errors: v.number(), mode: v.union(v.literal("normal"), v.literal("degraded"), v.literal("read_only")), updatedAt: v.number() }).index("by_workspace", ["workspaceId"])
  ,backupRecords: defineTable({ workspaceId: v.id("workspaces"), backupKey: v.string(), checksum: v.string(), exportedAt: v.number(), latestWriteAt: v.number(), rpoMs: v.number(), retentionUntil: v.number(), rtoMs: v.optional(v.number()), status: v.union(v.literal("exported"), v.literal("restored"), v.literal("deleted"), v.literal("failed")), deletedAt: v.optional(v.number()) }).index("by_workspace_key", ["workspaceId", "backupKey"])
});
