export type VaultResult = { status: "available"; value: string } | { status: "unsupported"; code: "VAULT_UNSUPPORTED" };
export type ProtectedVaultPort = Readonly<{ put(tenantId: string, key: string, value: string): void; get(tenantId: string, key: string): VaultResult }>;
export type ProtectedVault = ProtectedVaultPort;
export type ProtectedVaultHost = Readonly<{ put(tenantId: string, key: string, value: string): void; get(tenantId: string, key: string): string | undefined }>;
export function createProtectedVaultPort(host?: ProtectedVaultHost): ProtectedVaultPort {
  if (!host || typeof host.put !== "function" || typeof host.get !== "function") throw new Error("PROTECTED_VAULT_UNAVAILABLE");
  return Object.freeze({ put(tenantId, key, value) { if (!tenantId || !key || !value) throw new Error("VAULT_INPUT_INVALID"); host.put(tenantId, key, value); }, get(tenantId, key) { if (!tenantId || !key) return { status: "unsupported", code: "VAULT_UNSUPPORTED" }; try { const value = host.get(tenantId, key); return value ? { status: "available", value } : { status: "unsupported", code: "VAULT_UNSUPPORTED" }; } catch { return { status: "unsupported", code: "VAULT_UNSUPPORTED" }; } } });
}
/** Deterministic test port only; callers must supply an OS/vault-backed implementation in production. */
export function createInMemoryVault(options: { supported?: boolean } = {}): ProtectedVaultPort {
  const supported = options.supported === true; const values = new Map<string, string>(); const keyFor = (tenant: string, key: string) => `${tenant}\u0000${key}`;
  return Object.freeze({ put(tenantId, key, value) { if (!supported) throw new Error("VAULT_UNSUPPORTED"); if (!tenantId || !key || !value) throw new Error("VAULT_INPUT_INVALID"); values.set(keyFor(tenantId, key), value); }, get(tenantId, key) { if (!supported) return { status: "unsupported", code: "VAULT_UNSUPPORTED" }; const value = values.get(keyFor(tenantId, key)); return value === undefined ? { status: "unsupported", code: "VAULT_UNSUPPORTED" } : { status: "available", value }; } });
}
import { verify as verifySignature, type KeyObject } from "node:crypto";

export type ReleaseActivation = Readonly<{ approvedBy: string; timestamp: number }>;
export type ReleaseManifest = Readonly<{ version: "release-manifest/v1"; id: string; provenance: string; capabilities: readonly string[]; activation: ReleaseActivation }>;
export type ReleaseSignature = Readonly<{ version: "release-signature/v1"; algorithm: "Ed25519"; keyId: string; value: string }>;
export type Release = Readonly<{ manifest: ReleaseManifest; signature: ReleaseSignature }>;
export type TrustedReleaseKeys = Readonly<Record<string, string | KeyObject>>;
function canonical(value: unknown): string { if (typeof value === "string") return JSON.stringify(value); if (typeof value === "number" || typeof value === "boolean" || value === null) return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (typeof value === "object" && value !== null) { const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`; } throw new Error("RELEASE_MANIFEST_INVALID"); }
export function canonicalReleaseManifest(manifest: ReleaseManifest): string { return canonical({ activation: manifest.activation, capabilities: [...manifest.capabilities], id: manifest.id, provenance: manifest.provenance, version: manifest.version }); }
function validManifest(manifest: ReleaseManifest): boolean { return manifest.version === "release-manifest/v1" && Boolean(manifest.id) && /^sha256:[a-f0-9]+$/i.test(manifest.provenance) && manifest.capabilities.length > 0 && new Set(manifest.capabilities).size === manifest.capabilities.length && Boolean(manifest.activation.approvedBy) && Number.isFinite(manifest.activation.timestamp) && manifest.activation.timestamp > 0; }
export function verifyReleaseManifest(release: Release, trustedKeys: TrustedReleaseKeys): boolean { if (!validManifest(release.manifest) || release.signature.version !== "release-signature/v1" || release.signature.algorithm !== "Ed25519" || !release.signature.keyId || !/^[A-Za-z0-9+/]+={0,2}$/.test(release.signature.value)) return false; const key = trustedKeys[release.signature.keyId]; if (!key) return false; try { return verifySignature(null, Buffer.from(canonicalReleaseManifest(release.manifest)), key, Buffer.from(release.signature.value, "base64")); } catch { return false; } }
export function createReleaseController(options: Readonly<{ trustedKeys: TrustedReleaseKeys }>) { if (!options || !options.trustedKeys || Object.keys(options.trustedKeys).length === 0) throw new Error("RELEASE_TRUST_STORE_REQUIRED"); let active: Release | undefined; const verified = new Map<string, Release>(); return Object.freeze({ activate(release: Release) { if (!verifyReleaseManifest(release, options.trustedKeys)) throw new Error("RELEASE_VERIFICATION_FAILED"); const frozen = Object.freeze({ manifest: Object.freeze({ ...release.manifest, capabilities: Object.freeze([...release.manifest.capabilities]), activation: Object.freeze({ ...release.manifest.activation }) }), signature: Object.freeze({ ...release.signature }) }); verified.set(release.manifest.id, frozen); active = frozen; return { activeReleaseId: release.manifest.id, verification: "verified" as const }; }, rollback(releaseId: string, activation: ReleaseActivation) { const target = verified.get(releaseId); if (!target || !active || !activation.approvedBy || !Number.isFinite(activation.timestamp) || activation.timestamp <= 0) throw new Error("ROLLBACK_VERIFICATION_FAILED"); const rollbackOf = active.manifest.id; active = target; return { activeReleaseId: target.manifest.id, rollbackOf, verification: "verified" as const }; }, active: () => active }); }
export type AdapterContract = Readonly<{ name: string; version: string; capabilities: readonly string[]; limits: Readonly<Record<string, number>>; health(): Promise<{ healthy: boolean; code?: string }> }>;
export function createAdapterRegistry(vault: ProtectedVault) { const adapters = new Map<string, AdapterContract>(); return Object.freeze({ register(adapter: AdapterContract) { if (!adapter.name || !adapter.version || !adapter.capabilities.length || !Object.keys(adapter.limits).length || typeof adapter.health !== "function") throw new Error("ADAPTER_CONTRACT_INVALID"); if (Object.values(adapter.limits).some((limit) => !Number.isFinite(limit) || limit < 0)) throw new Error("ADAPTER_CONTRACT_INVALID"); adapters.set(adapter.name, Object.freeze({ ...adapter, capabilities: [...adapter.capabilities], limits: { ...adapter.limits } })); }, describe: (name: string) => adapters.get(name), credential: (tenantId: string, name: string) => { if (!adapters.has(name)) throw new Error("ADAPTER_UNSUPPORTED"); return vault.get(tenantId, name); } }); }
type LedgerEntry = { tenantId: string; type: "usage" | "credit" | "refund"; idempotencyKey: string; amountMicros: number; providerCostMicros: number; units: number };
export function createCommercialLedger() { const plans = new Map<string, { planId: string; includedUnits: number; unitPriceMicros: number }>(); const entries = new Map<string, LedgerEntry>(); const key = (tenantId: string, id: string) => `${tenantId}\u0000${id}`; return Object.freeze({ setPlan(input: { tenantId: string; planId: string; includedUnits: number; unitPriceMicros: number }) { if (!input.tenantId || input.includedUnits < 0 || input.unitPriceMicros < 0) throw new Error("PLAN_INVALID"); plans.set(input.tenantId, { ...input }); }, recordUsage(input: { tenantId: string; idempotencyKey: string; units: number; providerCostMicros: number }) { const previous = entries.get(key(input.tenantId, input.idempotencyKey)); if (previous) return { replayed: true, overageUnits: Math.max(0, previous.units - (plans.get(input.tenantId)?.includedUnits ?? 0)), chargedMicros: previous.amountMicros }; const plan = plans.get(input.tenantId); if (!plan || input.units < 0 || input.providerCostMicros < 0) throw new Error("USAGE_INVALID"); const priorUnits = [...entries.values()].filter(x => x.tenantId === input.tenantId && x.type === "usage").reduce((sum, x) => sum + x.units, 0); const overageUnits = Math.max(0, priorUnits + input.units - plan.includedUnits); const chargedMicros = Math.max(0, overageUnits - Math.max(0, priorUnits - plan.includedUnits)) * plan.unitPriceMicros; entries.set(key(input.tenantId, input.idempotencyKey), { ...input, type: "usage", amountMicros: chargedMicros }); return { replayed: false, overageUnits, chargedMicros }; }, grantCredit(input: { tenantId: string; idempotencyKey: string; amountMicros: number }) { entries.set(key(input.tenantId, input.idempotencyKey), { ...input, type: "credit", providerCostMicros: 0, units: 0 }); }, refund(input: { tenantId: string; idempotencyKey: string; amountMicros: number }) { entries.set(key(input.tenantId, input.idempotencyKey), { ...input, type: "refund", providerCostMicros: 0, units: 0 }); }, invoice(input: { tenantId: string; invoiceId: string }) { const rows = [...entries.values()].filter(x => x.tenantId === input.tenantId); return { tenantId: input.tenantId, invoiceId: input.invoiceId, chargedMicros: rows.filter(x => x.type === "usage").reduce((s,x) => s+x.amountMicros,0), providerCostMicros: rows.reduce((s,x) => s+x.providerCostMicros,0), creditMicros: rows.filter(x=>x.type === "credit").reduce((s,x)=>s+x.amountMicros,0), refundMicros: rows.filter(x=>x.type === "refund").reduce((s,x)=>s+x.amountMicros,0) }; } }); }
export function createPrivacyController(policy: { regions: readonly string[]; retentionMs: number }) { const records: { tenantId: string; region: string; subjectId: string; value: string; createdAt: number }[] = []; const incidents = new Set<string>(); const own = (tenantId: string, subjectId: string) => records.filter(x => x.tenantId === tenantId && x.subjectId === subjectId); return Object.freeze({ record(record: typeof records[number]) { if (!policy.regions.includes(record.region)) throw new Error("REGION_UNSUPPORTED"); records.push({ ...record }); }, supportAccess(input: { tenantId: string; supportId: string; consent: boolean }) { if (!input.consent) throw new Error("SUPPORT_CONSENT_REQUIRED"); return { tenantId: input.tenantId, supportId: input.supportId, access: "granted" as const }; }, export(input: { tenantId: string; subjectId: string }) { return own(input.tenantId, input.subjectId).map(x => ({ ...x })); }, delete(input: { tenantId: string; subjectId: string }) { const found = own(input.tenantId, input.subjectId); for (const record of found) records.splice(records.indexOf(record), 1); return { deleted: found.length }; }, sweep(now: number) { const expired = records.filter(x => now - x.createdAt > policy.retentionMs); for (const record of expired) records.splice(records.indexOf(record), 1); return { deleted: expired.length }; }, incident(input: { tenantId: string; idempotencyKey: string; severity: "low" | "high" }) { incidents.add(`${input.tenantId}\u0000${input.idempotencyKey}`); return { recorded: true }; } }); }
export type BackupCryptoPort = Readonly<{ encrypt(plain: string): string; decrypt(ciphertext: string): string }>;
export type BackupStoragePort = Readonly<{ put(key: string, value: string): void; get(key: string): string | undefined; remove(key: string): void }>;
export type BackupAuditPort = Readonly<{ append(event: Readonly<{ action: "backup.restore"; tenantId: string; snapshotId: string; idempotencyKey: string }>): void }>;
export type IsolatedRestoreTarget = Readonly<{ isolated: true; apply(records: readonly { tenantId: string; value: string }[]): Promise<void> | void }>;
type EncryptedSnapshot = Readonly<{ id: string; tenantId: string; exportedAt: number; schemaVersion: string; ciphertext: string }>;
type EncryptedBackupPolicy = Readonly<{ retainSnapshots: number; maxRpoMs: number; maxRtoMs: number; schemaVersion?: string; crypto?: BackupCryptoPort; storage?: BackupStoragePort; audit?: BackupAuditPort; restoreTarget?: IsolatedRestoreTarget; encrypt?: (plain: string) => string; decrypt?: (cipher: string) => string }>;
function backupSnapshotId(tenantId: string, exportedAt: number, schemaVersion: string) { return `${tenantId}:${schemaVersion}:${exportedAt}`; }
/** Encrypted backups require injected crypto, durable storage, audit, and isolated restore ports; no production fallback exists. */
export function createEncryptedBackupCoordinator(policy: EncryptedBackupPolicy) {
  if (!Number.isSafeInteger(policy.retainSnapshots) || policy.retainSnapshots < 1 || policy.maxRpoMs < 0 || policy.maxRtoMs < 0) throw new RangeError("BACKUP_POLICY_INVALID");
  const crypto = policy.crypto ?? (policy.encrypt && policy.decrypt ? { encrypt: policy.encrypt, decrypt: policy.decrypt } : undefined);
  const legacy = !policy.crypto && Boolean(crypto);
  if (!crypto || (!legacy && (!policy.storage || !policy.audit || !policy.restoreTarget))) throw new Error("BACKUP_PORTS_REQUIRED");
  const schemaVersion = policy.schemaVersion ?? "v1";
  const fallbackStorage = new Map<string, string>();
  const storage = policy.storage ?? { put: (key: string, value: string) => { fallbackStorage.set(key, value); }, get: (key: string) => fallbackStorage.get(key), remove: (key: string) => { fallbackStorage.delete(key); } };
  const audit = policy.audit ?? { append: () => undefined };
  const restoreTarget = policy.restoreTarget ?? { isolated: true as const, apply: () => undefined };
  const snapshots = new Map<string, EncryptedSnapshot[]>();
  const restored = new Map<string, { snapshotId: string; result: { restored: true; replayed: boolean; rpoMs: number; rtoMs: number; isolated: true; recordsRestored: number } }>();
  const retained = (tenantId: string) => snapshots.get(tenantId) ?? [];
  return Object.freeze({
    async export(input: { tenantId: string; exportedAt: number; records: readonly { tenantId: string; value: string }[] }) {
      if (!input.tenantId || !Number.isFinite(input.exportedAt)) throw new Error("BACKUP_INPUT_INVALID");
      const records = input.records.filter((record) => record.tenantId === input.tenantId).map((record) => ({ ...record })).sort((a, b) => a.value.localeCompare(b.value));
      const id = backupSnapshotId(input.tenantId, input.exportedAt, schemaVersion);
      const snapshot = Object.freeze({ id, tenantId: input.tenantId, exportedAt: input.exportedAt, schemaVersion, ciphertext: crypto.encrypt(JSON.stringify({ version: "encrypted-snapshot/v1", schemaVersion, tenantId: input.tenantId, exportedAt: input.exportedAt, records })) });
      storage.put(id, snapshot.ciphertext);
      const tenantSnapshots = retained(input.tenantId); tenantSnapshots.push(snapshot); while (tenantSnapshots.length > policy.retainSnapshots) { const expired = tenantSnapshots.shift(); if (expired) storage.remove(expired.id); } snapshots.set(input.tenantId, tenantSnapshots);
      return snapshot;
    },
    async restore(input: { snapshot: EncryptedSnapshot; tenantId: string; authorized: boolean; startedAt: number; completedAt: number; latestWriteAt: number; idempotencyKey?: string; isolated?: boolean }) {
      if (input.authorized !== true) throw new Error("RESTORE_AUTH_REQUIRED");
      const indexed = retained(input.tenantId).find((snapshot) => snapshot.id === input.snapshot.id); if (input.tenantId !== input.snapshot.tenantId || !indexed) throw new Error("RESTORE_TENANT_DENIED");
      if (input.snapshot.schemaVersion !== schemaVersion) throw new Error("RESTORE_SCHEMA_MISMATCH");
      if (indexed.tenantId !== input.snapshot.tenantId || indexed.schemaVersion !== input.snapshot.schemaVersion || indexed.exportedAt !== input.snapshot.exportedAt || indexed.ciphertext !== input.snapshot.ciphertext || input.snapshot.id !== backupSnapshotId(input.snapshot.tenantId, input.snapshot.exportedAt, input.snapshot.schemaVersion)) throw new Error("RESTORE_TENANT_DENIED");
      if (input.isolated === false || !restoreTarget.isolated) throw new Error("RESTORE_ISOLATION_REQUIRED");
      const idempotencyKey = input.idempotencyKey ?? input.snapshot.id;
      const previous = restored.get(`${input.tenantId}\u0000${idempotencyKey}`); if (previous) { if (previous.snapshotId !== input.snapshot.id) throw new Error("RESTORE_IDEMPOTENCY_CONFLICT"); return { ...previous.result, replayed: true as const }; }
      const ciphertext = storage.get(input.snapshot.id); if (ciphertext !== input.snapshot.ciphertext) throw new Error("RESTORE_SNAPSHOT_UNAVAILABLE");
      let payload: { version: string; schemaVersion: string; tenantId: string; exportedAt: number; records: { tenantId: string; value: string }[] }; try { payload = JSON.parse(crypto.decrypt(ciphertext)) as typeof payload; } catch { throw new Error("RESTORE_DECRYPTION_FAILED"); }
      const rpoMs = input.snapshot.exportedAt - input.latestWriteAt, rtoMs = input.completedAt - input.startedAt;
      if (payload.version !== "encrypted-snapshot/v1" || !Array.isArray(payload.records) || payload.schemaVersion !== schemaVersion || payload.schemaVersion !== input.snapshot.schemaVersion) throw new Error("RESTORE_SCHEMA_MISMATCH");
      if (payload.tenantId !== input.tenantId || payload.tenantId !== input.snapshot.tenantId || payload.exportedAt !== input.snapshot.exportedAt || payload.records.some((record) => !record || record.tenantId !== input.tenantId || typeof record.value !== "string") || rpoMs < 0 || rpoMs > policy.maxRpoMs || rtoMs < 0 || rtoMs > policy.maxRtoMs) throw new Error("DR_TARGET_VIOLATION");
      await restoreTarget.apply(Object.freeze(payload.records.map((record) => Object.freeze({ ...record }))));
      const result = Object.freeze({ restored: true as const, replayed: false as const, rpoMs, rtoMs, isolated: true as const, recordsRestored: payload.records.length }); restored.set(`${input.tenantId}\u0000${idempotencyKey}`, { snapshotId: input.snapshot.id, result }); audit.append({ action: "backup.restore", tenantId: input.tenantId, snapshotId: input.snapshot.id, idempotencyKey }); return result;
    },
    deleteTenant(tenantId: string) { const tenantSnapshots = retained(tenantId); for (const snapshot of tenantSnapshots) storage.remove(snapshot.id); snapshots.delete(tenantId); for (const key of restored.keys()) if (key.startsWith(`${tenantId}\u0000`)) restored.delete(key); return { deletedSnapshots: tenantSnapshots.length }; },
    retentionCount: (tenantId?: string) => tenantId ? retained(tenantId).length : [...snapshots.values()].reduce((total, entries) => total + entries.length, 0)
  });
}
export function createMigrationController() { const states = new Map<string, "expanded" | "rolled_back">(); return Object.freeze({ expand(version: string) { states.set(version, "expanded"); }, rollback(version: string) { if (states.get(version) !== "expanded") throw new Error("MIGRATION_ROLLBACK_DENIED"); states.set(version, "rolled_back"); return { version, state: "rolled_back" as const }; } }); }
export function createSetupDiagnostics(input: { platform: string; available: readonly string[]; required: readonly string[] }) { return Object.freeze({ run() { const missing = input.required.filter(x => !input.available.includes(x)); return { ready: missing.length === 0, platform: input.platform, missing, featureFlags: { releaseActivation: missing.length === 0, migrations: input.available.includes("node") } }; } }); }
