import {
  createProductShellState,
  productShellView,
  transitionProductShell,
  type ProductRoute,
  type ProductShellEvent,
  type ProductShellState,
  type ToolApproval
} from "./product-shell.js";

export type ProductShellController = Readonly<{ readonly state: ProductShellState; dispatch(event: ProductShellEvent): void }>;
export type BrowserContractCommand = "browser.health" | "browser.navigate" | "product.consent.resolve";
export type BrowserContractBoundary = Readonly<{ invoke(command: BrowserContractCommand, args: unknown): Promise<unknown> }>;
export type ProductEventPort = Readonly<{ subscribe(listener: (event: ProductShellEvent) => void): () => void }>;
const isKeyboardShortcut = (key: string) => key >= "1" && key <= "5";
const routeLabel = (route: ProductRoute) => route.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join(" ");
function element<K extends keyof HTMLElementTagNameMap>(document: Document, tag: K, attributes: Record<string, string> = {}, text?: string): HTMLElementTagNameMap[K] { const node = document.createElement(tag); for (const [name, value] of Object.entries(attributes)) node.setAttribute(name, value); if (text !== undefined) node.textContent = text; return node; }
function button(document: Document, text: string, attributes: Record<string, string>): HTMLButtonElement { return element(document, "button", { type: "button", ...attributes }, text); }
function appendNotice(document: Document, main: HTMLElement, view: ReturnType<typeof productShellView>) { if (!view.notice) return; const notice = element(document, "section", { class: `notice ${view.notice.kind}`, role: view.notice.kind === "error" ? "alert" : "status" }); notice.append(element(document, "strong", {}, view.notice.kind), element(document, "p", {}, view.notice.message ?? "")); if (view.notice.actionLabel) notice.append(button(document, view.notice.actionLabel, { "data-event": "recover" })); main.append(notice); }
function renderShell(document: Document, app: HTMLElement, state: ProductShellState) {
  const view = productShellView(state); app.replaceChildren(); app.append(element(document, "a", { class: "skip-link", href: "#product-main" }, "Skip to workspace content"));
  const background = element(document, "div", { "data-product-background": "true" }); const header = element(document, "header", { class: "topbar" }); header.append(element(document, "strong", {}, "K0"), element(document, "span", {}, "Commercial agent operations"), button(document, "Connection status", { "data-event": "offline" })); background.append(header);
  const layout = element(document, "div", { class: "layout" }); const nav = element(document, "nav", { "aria-label": "Workspace navigation" }); nav.append(element(document, "h2", {}, "Workspace")); for (const [index, route] of view.routes.entries()) nav.append(button(document, `${index + 1}. ${routeLabel(route)}`, { "data-route": route, "aria-current": state.route === route ? "page" : "false" }));
  const main = element(document, "main", { id: "product-main", tabindex: "-1", "aria-label": view.mainLandmarkLabel }); main.append(element(document, "p", { class: "eyebrow" }, state.workspaceName), element(document, "h1", {}, routeLabel(state.route)), element(document, "p", {}, "Use keyboard shortcuts 1–5 to change workspaces. Tool requests always require explicit consent.")); appendNotice(document, main, view); const runs = element(document, "section", { "aria-labelledby": "agent-runs" }); runs.append(element(document, "h2", { id: "agent-runs" }, "Agent runs"), element(document, "p", {}, "Tool approvals are supplied by the provider and reflect its current consent state."), button(document, "Load workspace evidence", { "data-event": "data-loading" }), button(document, "Show empty workspace", { "data-event": "data-empty" }), button(document, "Report workspace error", { "data-event": "recovery-failed" })); main.append(runs);
  if (state.route === "browser") { const browser = element(document, "section", { "aria-labelledby": "browser-view" }); browser.append(element(document, "h2", { id: "browser-view" }, "Browser"), element(document, "p", {}, "Navigate through the injected capability-scoped browser contract."), button(document, "Navigate to approved page", { "data-event": "browser-navigate" })); main.append(browser); }
  if (state.route === "tool-approvals") { const approvals = element(document, "section", { "aria-labelledby": "tool-approvals-view" }); approvals.append(element(document, "h2", { id: "tool-approvals-view" }, "Tool Approvals"), element(document, "p", {}, state.approval ? `Approval waiting: ${state.approval.toolName}` : "No tool approval is waiting.")); main.append(approvals); }
  const aside = element(document, "aside", { "aria-label": "Trace and evidence" }); const trace = element(document, "ol"); if (view.trace.length) for (const entry of view.trace) trace.append(element(document, "li", {}, `${entry.sequence}. ${entry.event} (${entry.commandId})`)); else trace.append(element(document, "li", {}, "No trace events yet.")); aside.append(element(document, "h2", {}, "Trace evidence"), trace); layout.append(nav, main, aside); background.append(layout); app.append(background);
  if (state.status === "awaiting-consent" && view.consent) { background.setAttribute("aria-hidden", "true"); (background as HTMLElement & { inert: boolean }).inert = true; const dialog = element(document, "section", { class: "consent", "aria-labelledby": "consent-title", role: "dialog", "aria-modal": "true" }); dialog.append(element(document, "h2", { id: "consent-title" }, view.consent.title), element(document, "p", {}, view.consent.description), button(document, view.consent.confirmLabel, { "data-event": "approve" }), button(document, "Deny", { "data-event": "deny" })); app.append(dialog); }
}
function browserNavigationApproval(): ToolApproval { return { commandId: "browser-navigate-1", toolName: "browser.navigate", reason: "Navigate to the provider-approved browser page.", risk: "medium", args: { id: "browser-navigate-1", url: "https://example.com" } }; }
export function mountProductShell(document: Document, options: { browser?: BrowserContractBoundary; events?: ProductEventPort } = {}): ProductShellController {
  const app = document.querySelector<HTMLElement>("#app"); if (!app) throw new Error("PRODUCT_APP_ROOT_REQUIRED"); let state = createProductShellState({ workspaceId: "local-workspace", workspaceName: "Local workspace" }); let returnFocusSelector: string | undefined;
  const render = (focus?: "main" | "dialog" | "return") => { renderShell(document, app, state); if (focus === "main") document.querySelector<HTMLElement>("#product-main")?.focus(); if (focus === "dialog") document.querySelector<HTMLElement>('[data-event="approve"]')?.focus(); if (focus === "return" && returnFocusSelector) document.querySelector<HTMLElement>(returnFocusSelector)?.focus(); };
  const dispatch = (event: ProductShellEvent) => { const previous = state; state = transitionProductShell(state, event); const focus = event.type === "NAVIGATED" || event.type === "KEYBOARD_NAVIGATION" ? "main" : event.type === "TOOL_APPROVAL_REQUESTED" ? "dialog" : previous.status === "awaiting-consent" && state.status === "ready" ? "return" : undefined; render(focus); };
  app.addEventListener("click", (event) => { const target = (event.target as HTMLElement).closest<HTMLButtonElement>("button"); if (!target) return; const route = target.dataset.route as ProductRoute | undefined; if (route) { dispatch({ type: "NAVIGATED", route }); return; } if (target.dataset.event === "offline") dispatch({ type: "CONNECTION_OFFLINE" }); if (target.dataset.event === "recover") dispatch({ type: "RECOVERY_REQUESTED" }); if (target.dataset.event === "data-loading") dispatch({ type: "DATA_LOADING" }); if (target.dataset.event === "data-empty") dispatch({ type: "DATA_EMPTY" }); if (target.dataset.event === "recovery-failed") dispatch({ type: "RECOVERY_FAILED", message: "Workspace service is unavailable." }); if (target.dataset.event === "browser-navigate") { returnFocusSelector = '[data-event="browser-navigate"]'; dispatch({ type: "TOOL_APPROVAL_REQUESTED", approval: browserNavigationApproval() }); } if (target.dataset.event === "approve" && state.approval) { const approval = state.approval; dispatch({ type: "TOOL_APPROVAL_RESOLVED", approved: true }); const command = approval.toolName as BrowserContractCommand; void options.browser?.invoke("product.consent.resolve", { commandId: approval.commandId, approved: true }).then(() => options.browser?.invoke(command, approval.args ?? { id: approval.commandId, confirmed: true })).then((value) => { const result = value as { status?: "completed" | "denied" | "unknown"; receipt?: { id?: string } }; dispatch({ type: "BROWSER_ACTION_COMPLETED", commandId: result.receipt?.id ?? approval.commandId, toolName: command as Exclude<BrowserContractCommand, "browser.health" | "product.consent.resolve">, status: result.status ?? "unknown" }); }).catch(() => dispatch({ type: "BROWSER_ACTION_COMPLETED", commandId: approval.commandId, toolName: command as Exclude<BrowserContractCommand, "browser.health" | "product.consent.resolve">, status: "unknown" })); } if (target.dataset.event === "deny") dispatch({ type: "TOOL_APPROVAL_RESOLVED", approved: false }); });
  document.addEventListener("keydown", (event) => { if (state.status === "awaiting-consent" && !event.metaKey && !event.ctrlKey && isKeyboardShortcut(event.key)) { event.preventDefault(); return; } if (!event.metaKey && !event.ctrlKey && isKeyboardShortcut(event.key)) dispatch({ type: "KEYBOARD_NAVIGATION", key: event.key }); if (state.status !== "awaiting-consent") return; if (event.key === "Escape") { event.preventDefault(); dispatch({ type: "TOOL_APPROVAL_RESOLVED", approved: false }); return; } if (event.key === "Tab") { const controls = Array.from(document.querySelectorAll<HTMLElement>('[role="dialog"] button')); if (!controls.length) return; event.preventDefault(); const current = controls.indexOf(document.activeElement as HTMLElement); controls[(current + (event.shiftKey ? controls.length - 1 : 1)) % controls.length]?.focus(); } });
  render(); options.events?.subscribe(dispatch); void options.browser?.invoke("browser.health", {}).then((value) => { if ((value as { health?: { healthy?: boolean } }).health?.healthy === false) dispatch({ type: "CONNECTION_OFFLINE" }); }).catch(() => dispatch({ type: "CONNECTION_OFFLINE" })); return { get state() { return state; }, dispatch };
}
